#!/bin/bash
# Vault is managed by ArgoCD as a subchart of realestate-prod in the prod namespace
echo "Since Vault is in production mode, you must initialize and unseal it manually."
echo "Run the following commands once ArgoCD has deployed the vault pod:"
echo ""
echo "1. Initialize Vault and securely save the keys (this only happens ONCE EVER):"
echo "   kubectl exec -n prod realestate-prod-vault-0 -- vault operator init -key-shares=1 -key-threshold=1 > cluster-keys.txt"
echo "   cat cluster-keys.txt"
echo ""
echo "2. Unseal Vault (you must do this every time the pod restarts):"
echo "   kubectl exec -n prod realestate-prod-vault-0 -- vault operator unseal <YOUR_UNSEAL_KEY>"
echo ""
echo "3. Login using the Initial Root Token:"
echo "   kubectl exec -n prod realestate-prod-vault-0 -- vault login <YOUR_ROOT_TOKEN>"
echo ""
echo "4. After doing this, run ./configure-vault.sh to write secrets and configure ESO auth."
