#!/bin/bash
echo "Since Vault is now in production mode, you must initialize and unseal it manually."
echo "Run the following commands once your cloud cluster is up:"
echo ""
echo "1. Initialize Vault and securely save the keys (this only happens once):"
echo "   kubectl exec -n vault vault-0 -- vault operator init -key-shares=1 -key-threshold=1 > cluster-keys.txt"
echo "   cat cluster-keys.txt"
echo ""
echo "2. Unseal Vault using the Unseal Key from the output (you must do this every time the pod restarts!):"
echo "   kubectl exec -n vault vault-0 -- vault operator unseal <YOUR_UNSEAL_KEY>"
echo ""
echo "3. Login using the Initial Root Token:"
echo "   kubectl exec -n vault vault-0 -- vault login <YOUR_ROOT_TOKEN>"
echo ""
echo "4. After doing this, you can run ./configure-vault.sh to recreate your secrets."
