# Global settings for all pods
global:
  replicaCount: 1
  configServerUrl: "http://config-service-svc:80"

# List every microservice here. The template will loop through this list.
microservices:
  gateway-service:
    image: junaiduthman/gateway-service
    tag: 7-48cd426
    port: 8080
    type: springboot
    serviceType: ClusterIP   # Ingress is now the entry point — no need for LoadBalancer
    needsConfigServer: true

  property-microservice:
    image: junaiduthman/property-management-service
    tag: 4-96ad5ab
    port: 8080
    type: springboot
    needsConfigServer: true

  user-management-service:
    image: junaiduthman/user-management-service
    tag: 8-ff469eb
    port: 8080
    type: springboot
    needsConfigServer: true

  rental-agreement-microservice:
    image: junaiduthman/rental-agreement-v2
    tag: 4-6892e92
    port: 8080
    type: springboot
    needsConfigServer: true

  ml-pricesuggestionmodel:
    image: junaiduthman/ml-pricesuggestionmodel
    tag: 5-7e4c672
    port: 5000
    type: python

  property-recommendation-engine:
    image: junaiduthman/property-recommendation-engine
    tag: 4-b3ecdaf
    port: 5000
    type: python

  tenant-risk-scoring:
    image: junaiduthman/tenant-risk-scoring
    tag: 4-0725daf
    port: 5000
    type: python

  predictive-heatmaps-of-neighborhood-price-evolution:
    image: junaiduthman/predictive-heatmaps-of-neighborhood-price-evolution
    tag: 19-cb1f258
    port: 5000
    type: python

  notification-service:
    image: junaiduthman/notification-service
    tag: 4-7316ef3
    port: 8080
    type: springboot
    needsConfigServer: true

  config-service:
    image: junaiduthman/config-service
    tag: 7-bf1763b
    port: 8888
    type: springboot

  auth-server:
    image: junaiduthman/authorization-service
    tag: 5-01e5959
    port: 8080
    type: springboot
    needsConfigServer: true

  public-app:
    image: junaiduthman/public-app
    tag: 7-610f941
    port: 80
    type: angular
    serviceType: ClusterIP   # Ingress is now the entry point — no need for LoadBalancer

  


