# Global settings for all pods
global:
  replicaCount: 1

# List every microservice here. The template will loop through this list.
microservices:
  gateway-service:
    image: junaiduthman/gateway-service
    tag: 6-51c1716
    port: 8080
    type: springboot
    serviceType: LoadBalancer

  property-microservice:
    image: junaiduthman/property-management-service
    tag: 4-96ad5ab
    port: 8080
    type: springboot

  user-management-service:
    image: junaiduthman/user-management-service
    tag: 8-ff469eb
    port: 8080
    type: springboot

  RentalAgreement-microservice:
    image: junaiduthman/rental-agreement-v2
    tag: 4-6892e92
    port: 8080
    type: springboot

  ml-pricesuggestionmodel:
    image: junaiduthman/ml-pricesuggestionmodel
    tag: 5-7e4c672
    port: 5000
    type: python

  property-recommendation-engine:
    image: junaiduthman/property-recommendation-engine
    tag: latest
    port: 5000
    type: python

  tenant-risk-scoring:
    image: junaiduthman/tenant-risk-scoring
    tag: 4-0725daf
    port: 5000
    type: python

  predictive-heatmaps-of-neighborhood-price-evolution:
    image: junaiduthman/predictive-heatmaps-of-neighborhood-price-evolution
    tag: 19-cb1f258
    port: 5000
    type: python

  notification-service:
    image: junaiduthman/notification-service
    tag: 4-7316ef3
    port: 8080
    type: springboot

  config-service:
    image: junaiduthman/config-service
    tag: 6-f11b440
    port: 8080
    type: springboot

  auth-server:
    image: junaiduthman/authorization-service
    tag: 4-e35a0a3
    port: 8080
    type: springboot

  public-app:
    image: junaiduthman/public-app
    tag: 7-610f941
    port: 6000
    type: angular
    serviceType: LoadBalancer

  


