---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-passwords
  namespace: prod
spec:
  encryptedData:
    mysql-root-password: AgAt5r45vMiE++n2bGNy8OzowUt60bdM4mrFfFwjHdT4rycM8JEcyhTjN6xLm+Oc9yVJX8q0O67iDv5QkEqDMseyIm0+/wUGR0+pX5uy+0P72j4vOt/T7hLMAU76blhkPg+53OfcWN5GqV99alORO8vkeoASPwCqV0eLCxo51wVHTXKwB7H7qDnCqtY8GHqiifUxp4mjElQseEFkn3QHwbulA21sMalLwTEIxhvRLGfpl63cGdVLgQfiLdLv02KwLqtue7tW18JFXk0N82qWjDJLiNox5x4fUqUzllo01FnUR8R75HVotUgVdeE6Ai4Ev62pCQb2p46k5pMU/njzTahXnuMmPE8M+1ahPzBg5J8M3mkEiiC9EwmxdPZs1uV/VZclbG/SnL8X+a3Fn0mULd5XHw6d/dHMP1N3xM7oyZD+knU1cNch/vk22xOwjpEfQFGUZ9hGv+96I0xY9OsYibj1Kphgjae3RJcQlJX3TDGGUVumHBUWtAlreypBKJSqkzWxblZZCwqrEamMj9uooXAdzMpfK7Z+xJD8GGpDz70xPriWJdUuu/mtz54wfG8PNwRiQly2R/mlACzqqi28lQB6vWahye98cwUnm4FjRPgHffXsd9U4vNwzufZpjWoPVfbPwWCzyek3x5xLon8qYzB2BkoL+mYJg/k2GnPNigD0PYjFDMYnoWfQDiv7eitRFh+fkWky
  template:
    metadata:
      name: mysql-passwords
      namespace: prod
