apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: PROD_DB_PASSWORD
      remoteRef:
        key: realestate/mysql
        property: root-password
    - secretKey: SECRET_KEY
      remoteRef:
        key: realestate/app
        property: jwt-secret
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: realestate/app
        property: oauth-secret