apiVersion: v1
kind: Secret
metadata:
  name: mysql-passwords
type: Opaque
stringData:
  # this approach only for dev!!!! Takes the password from values.yaml under global.databasePassword, defaulting to 'root' if not set
  mysql-root-password: {{ .Values.global.databasePassword | default "root" | quote }}
