{{- range $serviceName, $serviceConfig := .Values.microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: {{ $.Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      {{- if $serviceConfig.needsConfigServer }}
      initContainers:
        - name: wait-for-config-server
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup config-service-svc; do echo waiting for config-server; sleep 2; done"]
      {{- end }}
      containers:
        - name: {{ $serviceName }}-container
          image: "{{ $serviceConfig.image }}:{{ $serviceConfig.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $serviceConfig.port }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: PORT
              value: "{{ $serviceConfig.port }}"
          {{- if $serviceConfig.needsConfigServer }}
            - name: CONFIG_SERVER_URL
              value: "{{ $.Values.global.configServerUrl }}"
          {{- end }}

          # # Dynamic Liveness Probe based on microservice type
          # livenessProbe:
          #   httpGet:
          #     {{- if eq $serviceConfig.type "springboot" }}
          #     path: /actuator/health
          #     {{- else if eq $serviceConfig.type "python" }}
          #     path: /health
          #     {{- end }}
          #     port: {{ $serviceConfig.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
            
          # # Dynamic Readiness Probe based on microservice type
          # readinessProbe:
          #   httpGet:
          #     {{- if eq $serviceConfig.type "springboot" }}
          #     path: /actuator/health
          #     {{- else if eq $serviceConfig.type "python" }}
          #     path: /health
          #     {{- end }}
          #     port: {{ $serviceConfig.port }}
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
---
{{- end }}
