apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-db
  labels:
    app: notification-db
spec:
  serviceName: "notification-db-svc"
  replicas: 1
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: notifications
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: notification-db-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: notification-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-db-svc
  labels:
    app: notification-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: notification-db
  clusterIP: None
